### ISSUE TITLE
Trying to set up Owntracks on a Raspberry Pi - how to set up the dns domain for quicksetup

### ISSUE THREAD

**Issue by Bow3ryList** [owntracks/quicksetup#64]
I'm not that experienced in trying to set up stuff on a raspberry pi but I wanted to give this a go so apologies if the answer is really simple.

I'm trying to install the quicksetup on the ras-pi but I'm not sure what to put into the dns_domain. I have set up the pi to act as a server and opened the port 80 so that it is accessible to the internet however when I put the IP adress as the the domain I get an error about using incorrect characters. Do I need to point domain name using an A record to the ras pi to allow the installation to finish or am is my understanding of how this works incorrect?

Thanks in advance for any help

Kind regards,

Tom

**Comment by aparker21** [comment]
@Bow3ryList I am also a novice with Raspberry Pi and doing the same thing. . . .I am getting a fatal error about my domain name.  I don't have it registered anywhere. . . how do I set up the A record that will allow me to get Let's Encrypt set up correctly??  Can I use duckdns?  What is the simplest and best option for a novice like myself?

**Comment by Bow3ryList** [comment]
Hi @aparker21

I'm not that familiar with duck dns, but reading a little about it looks like it might work if can get the domain to point to your raspberry pi IP address.

I purchased a domain name from reg123 and the pointed the domain to my pi to get the installation to work.

After it was installed, when ever my IP address changed it would stop working (my Internet provided does not offer fixed IP addresses, so I ended up using cloud flare to update the record when the IP address changes).

Not sure if any of this info will help, but good luck!

**Comment by aparker21** [comment]
That is very helpful. I have it pointing to my main IP but not the
raspberry pi IP.  That might be the issue. It is trying to resolve
everything on the router. I'm a bit confused on that though as I have had
owntracks pointing to another domain via duck DNS that goes to my Home
Assistant server and it just points to my main IP address and not the Home
Assistant IP address. Of course, that integration is not working right now,
but it was.  I will do some searching and check into adding cloudflare as
well. I wonder if the router is trying to point to the Home Assistant
server instead of the raspberry pi. Thank you for the information!!!  I
truly appreciate the help!

**Comment by Bow3ryList** [comment]
It might have been my IP address that I pointed it to now that you mention it. I'll check when I get a chance.

I checked the pi was working as a webserver first by following this page:

https://thepi.io/how-to-set-up-a-web-server-on-the-raspberry-pi/

Once I was able to access the pi from the web (with the router correctly set up), I used an A record to point my domain to the IP address I used to access the pi.

The installation worked without any issues after that.

This is the video I used to get cloudflare to work

https://m.youtube.com/watch?v=rI-XxnyWFnM&t=1s&pp=2AEBkAIB

Hope that helps

**Comment by aparker21** [comment]
I truly appreciate your help!  I think you are 100% correct. The router
just doesn't know how to route the traffic and I think you are on to
something with the web server. I will check that out. I appreciate the
links and all your help!!!

**Comment by aparker21** [comment]
You are amazing!!!!  I went to the web server setup and followed those
instructions.  I skipped steps 1-4 and only updated everything EXCEPT PHP
on step 5 since I am not actually trying to host a website right now. On
step 6 I used that info to set up the Port forwarding.  See below for more
details:

Owntracks already had mysql and nginx installed so those steps ended up
being for naught but I did update the nginx Default file and also added
Port Forwarding in PfSense via the NAT under Firewall settings instead of
just having the ports open.  ./bootstrap.sh ran and seems to have
completed.   It shows ok=48 changed=31 unrachable=0 failed=0 skipped=6
rescued=0 ignored=0.  I think I am good to go now??

Sincerely,
Aaron Parker

**Comment by jpmens** [comment]
> Owntracks already had mysql installed

No.

> also added Port Forwarding

which I seem to recall telling you by email this morning.

Be that as it may, glad you got it going. Whether or not that is all depends on whether the apps work, but you'll find out soon enough, I assume.

I am now closing https://github.com/owntracks/quicksetup/issues/74

**Comment by aparker21** [comment]
How do I send the .otcr file to myself?

I am trying to send the .otcr file to myself so I can input it from my
Android Owntracks app, but I am unable to send the file to myself due to
the file type being unrecognized by everything.  Any suggestions?

Sincerely,
Aaron Parker

**Comment by jpmens** [comment]
By mail as an attachment.

**Comment by aparker21** [comment]
It won't send.  It says the file is unrecognized.

Sincerely,
Aaron Parker

**Comment by jpmens** [comment]
what is "it" ?

**Comment by aparker21** [comment]
The otcr file to configure owntracks on mobile

**Comment by jpmens** [comment]
You're going to have to use more words if you want us to help you. How are you trying to send yourself that file per email and what type of mail client are you using which won't let you attach an arbitrary file?!

Also you've not reacted to my saying you can also login to the `<yourdomain>/owntracks/` page to click on a link directly from your Android/iOS mobile device to perform autoconfiguration, assuming you've correctly configured `configuration.yaml` before running `./bootstrap.sh`

**Comment by aparker21** [comment]
I'm sorry for the lack of info.

I am trying to send the .otcr user file via gmail so that i can access it
from my mobile phone and load that file into Owntracks App on the phone.  I
also tried using Proton Drive and Proton Mail, but I am having issues
getting to them from the linux machine for some reason. I might see if I
can SSH into it and grab it that way

Sincerely,
Aaron Parker
